"""Synthetic faulty CSV files for API tests, generated by the core."""

from __future__ import annotations

import io
from datetime import timedelta

import tabayyun_core as tc


def faulty_csv(faults: list[str], *, late_minutes: int | None = None) -> bytes:
    batch = tc.synth(n=2880, faults=faults)
    ts = batch.column("ts").to_pylist()
    values = batch.column("value").to_pylist()
    quality = batch.column("quality").to_pylist()
    buf = io.StringIO()
    buf.write("ts,value,quality" + (",arrived" if late_minutes is not None else "") + "\n")
    for t, v, q in zip(ts, values, quality, strict=True):
        row = f"{t.isoformat()},{'' if v is None else f'{v:.4f}'},{q}"
        if late_minutes is not None:
            row += f",{(t + timedelta(minutes=late_minutes)).isoformat()}"
        buf.write(row + "\n")
    return buf.getvalue().encode()
